### ISSUE TITLE
Missing "RandomizerSettingsUpdated.xml" file

### ISSUE THREAD

**Issue by Vadnic8** [lashoun/upgraded-fefates-randomizer#8]
i was using your randomizer but when i go through the python code editing section, i run the updated_randomizer.py scripts and get this feedback. 

Traceback (most recent call last):
  File "C:\Users\Johnson\Desktop\Files\Roms\upgraded-fefates-randomizer-master\upgraded-fefates-randomizer-master\updated_randomizer.py", line 1714, in <module>
    fatesRandomizer.run()
  File "C:\Users\Johnson\Desktop\Files\Roms\upgraded-fefates-randomizer-master\upgraded-fefates-randomizer-master\updated_randomizer.py", line 1636, in run
    row = [name, self.readSwitchedCharacterName(name), className]
  File "C:\Users\Johnson\Desktop\Files\Roms\upgraded-fefates-randomizer-master\upgraded-fefates-randomizer-master\updated_randomizer.py", line 1261, in readSwitchedCharacterName
    raise ValueError('Character named "{}" not found'.format(characterName))
ValueError: Character named "Benny" not found
or
ValueError: Character named "Nyx" not found

this causes the scripts to generate the "ClassSpread.csv" but not the "RandomizerSettingsUpdated.xml"

i was using the fates_gay_v140_upgraded_decompressed RomFS data.
and following your guide and suggestions since first time randomizing. 

modifiers chosen
python updated_randomizer.py -epa -dlts -dbsr

please let me know what i might need to do next time to get this to run correctly

**Comment by lashoun** [comment]
Hi, I've tried your command and it worked fine on my side so the problem must lie in your `RandomizerSettings.xml` file. Could you tell me what options you checked when you used the jar file? Apparently my script doesn't find Benny or Nyx in it, probably because they're missing. Maybe you picked Birthright in the jar file? Then you would have to add `-g "Birthright"` to your command:
`python updated_randomizer.py -epa -dlts -dbsr -g "Birthright"`

**Comment by lashoun** [comment]
Closing the issue, feel free to reopen if needed.
